# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Data.proto',
  package='format',
  serialized_pb=_b('\n\nData.proto\x12\x06\x66ormat\"0\n\x04\x44\x61ta\x12\x0e\n\x06\x61\x63tion\x18\x01 \x02(\t\x12\x18\n\x03\x63\x61r\x18\x02 \x01(\x0b\x32\x0b.format.Car\"Z\n\x06\x45ngine\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\r\x12\x14\n\x0cnumCylinders\x18\x02 \x01(\r\x12\x0e\n\x06maxRpm\x18\x03 \x01(\r\x12\x18\n\x10manufacturerCode\x18\x04 \x01(\t\"C\n\x0b\x46uelFigures\x12\r\n\x05speed\x18\x01 \x01(\r\x12\x0b\n\x03mpg\x18\x02 \x01(\x02\x12\x18\n\x10usageDescription\x18\x03 \x01(\t\",\n\x0c\x41\x63\x63\x65leration\x12\x0b\n\x03mph\x18\x01 \x01(\r\x12\x0f\n\x07seconds\x18\x02 \x01(\x02\"V\n\x12PerformanceFigures\x12\x14\n\x0coctaneRating\x18\x01 \x01(\r\x12*\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x0b\x32\x14.format.Acceleration\"\xa5\x02\n\x03\x43\x61r\x12\x11\n\townerName\x18\x01 \x01(\t\x12\x14\n\x0cserialNumber\x18\x02 \x02(\x04\x12\x11\n\tmodelYear\x18\x03 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\x13\n\x0bvehicleCode\x18\x05 \x01(\t\x12\x1e\n\x06\x65ngine\x18\x06 \x01(\x0b\x32\x0e.format.Engine\x12(\n\x0b\x66uelFigures\x18\x07 \x01(\x0b\x32\x13.format.FuelFigures\x12\x36\n\x12performanceFigures\x18\t \x01(\x0b\x32\x1a.format.PerformanceFigures\x12\x14\n\x0cmanufacturer\x18\n \x01(\t\x12\r\n\x05model\x18\x0b \x01(\t\x12\x18\n\x10\x61\x63tivationalCode\x18\x0c \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='format.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='format.Data.action', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='car', full_name='format.Data.car', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=70,
)


_ENGINE = _descriptor.Descriptor(
  name='Engine',
  full_name='format.Engine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capacity', full_name='format.Engine.capacity', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numCylinders', full_name='format.Engine.numCylinders', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxRpm', full_name='format.Engine.maxRpm', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manufacturerCode', full_name='format.Engine.manufacturerCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=162,
)


_FUELFIGURES = _descriptor.Descriptor(
  name='FuelFigures',
  full_name='format.FuelFigures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='format.FuelFigures.speed', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mpg', full_name='format.FuelFigures.mpg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usageDescription', full_name='format.FuelFigures.usageDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=231,
)


_ACCELERATION = _descriptor.Descriptor(
  name='Acceleration',
  full_name='format.Acceleration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mph', full_name='format.Acceleration.mph', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='format.Acceleration.seconds', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=277,
)


_PERFORMANCEFIGURES = _descriptor.Descriptor(
  name='PerformanceFigures',
  full_name='format.PerformanceFigures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='octaneRating', full_name='format.PerformanceFigures.octaneRating', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='format.PerformanceFigures.acceleration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=365,
)


_CAR = _descriptor.Descriptor(
  name='Car',
  full_name='format.Car',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerName', full_name='format.Car.ownerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='format.Car.serialNumber', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelYear', full_name='format.Car.modelYear', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='format.Car.code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleCode', full_name='format.Car.vehicleCode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='engine', full_name='format.Car.engine', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fuelFigures', full_name='format.Car.fuelFigures', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='performanceFigures', full_name='format.Car.performanceFigures', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='format.Car.manufacturer', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='format.Car.model', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activationalCode', full_name='format.Car.activationalCode', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=661,
)

_DATA.fields_by_name['car'].message_type = _CAR
_PERFORMANCEFIGURES.fields_by_name['acceleration'].message_type = _ACCELERATION
_CAR.fields_by_name['engine'].message_type = _ENGINE
_CAR.fields_by_name['fuelFigures'].message_type = _FUELFIGURES
_CAR.fields_by_name['performanceFigures'].message_type = _PERFORMANCEFIGURES
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Engine'] = _ENGINE
DESCRIPTOR.message_types_by_name['FuelFigures'] = _FUELFIGURES
DESCRIPTOR.message_types_by_name['Acceleration'] = _ACCELERATION
DESCRIPTOR.message_types_by_name['PerformanceFigures'] = _PERFORMANCEFIGURES
DESCRIPTOR.message_types_by_name['Car'] = _CAR

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.Data)
  ))
_sym_db.RegisterMessage(Data)

Engine = _reflection.GeneratedProtocolMessageType('Engine', (_message.Message,), dict(
  DESCRIPTOR = _ENGINE,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.Engine)
  ))
_sym_db.RegisterMessage(Engine)

FuelFigures = _reflection.GeneratedProtocolMessageType('FuelFigures', (_message.Message,), dict(
  DESCRIPTOR = _FUELFIGURES,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.FuelFigures)
  ))
_sym_db.RegisterMessage(FuelFigures)

Acceleration = _reflection.GeneratedProtocolMessageType('Acceleration', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATION,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.Acceleration)
  ))
_sym_db.RegisterMessage(Acceleration)

PerformanceFigures = _reflection.GeneratedProtocolMessageType('PerformanceFigures', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCEFIGURES,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.PerformanceFigures)
  ))
_sym_db.RegisterMessage(PerformanceFigures)

Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), dict(
  DESCRIPTOR = _CAR,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:format.Car)
  ))
_sym_db.RegisterMessage(Car)


# @@protoc_insertion_point(module_scope)
